name: Update Pull Request Target

on:
  push:
    branches:
      - feature/sprint35

jobs:
  update_pr_target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Pull Requests targeting sprint34
        id: find_pull_requests
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          PR_LIST=$(gh pr list --state open --base feature/sprint34 --json number)
          echo "pr_list=$PR_LIST" >> $GITHUB_OUTPUT

      - name: Extract PR numbers
        id: extract_pr_numbers
        run: |
          PR_LIST='${{ steps.find_pull_requests.outputs.pr_list }}'
          PR_NUMBERS=$(echo $PR_LIST | jq -r '.[].number | tostring' | paste -sd ',')
          PR_NUMBER_LIST="[$PR_NUMBERS]"
          echo "pr_number_list=$PR_NUMBER_LIST" >> $GITHUB_OUTPUT

      - name: Update PR targets
        if: steps.extract_pr_numbers.outputs.pr_number_list != ''
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          # PR_NUMBERS変数から括弧とスペースを削除し、配列として処理
          PR_NUMBERS_STR=$(echo ${{steps.extract_pr_numbers.outputs.pr_number_list}} | tr -d '[]' | tr ',' ' ')
          for PR_NUMBER in $PR_NUMBERS_STR; do
            echo "Editing PR: $PR_NUMBER"
            gh pr edit $PR_NUMBER --base feature/sprint35
          done
