name: Update Pull Request Target

on:
  push:
    branches:
      - feature/KP2-A/sprint*

jobs:
  update_pr_target:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get base branch
        timeout-minutes: 1
        id: get_base_branch
        run: |
          BRANCH_NAME=$(git branch -r | grep 'feature/KP2-A/sprint' | head -n 1 | sed 's/origin\///'  | sed 's/^\s*//')
          echo "base_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Find Pull Requests targeting sprint34
        id: find_pull_requests
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          PR_LIST=$(gh pr list --state open --base ${{steps.get_base_branch.outputs.base_branch}} --json number)
          echo "pr_list=$PR_LIST" >> $GITHUB_OUTPUT

      - name: Extract PR numbers
        id: extract_pr_numbers
        run: |
          PR_LIST='${{ steps.find_pull_requests.outputs.pr_list }}'
          PR_NUMBERS=$(echo $PR_LIST | jq -r '.[].number | tostring' | paste -sd ',')
          PR_NUMBER_LIST="[$PR_NUMBERS]"
          echo "pr_number_list=$PR_NUMBER_LIST" >> $GITHUB_OUTPUT

      - name: Update PR targets
        if: steps.extract_pr_numbers.outputs.pr_number_list != ''
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          # PR_NUMBERS変数から括弧とスペースを削除し、配列として処理
          PR_NUMBERS_STR=$(echo ${{steps.extract_pr_numbers.outputs.pr_number_list}} | tr -d '[]' | tr ',' ' ')
          for PR_NUMBER in $PR_NUMBERS_STR; do
            echo "Editing PR: $PR_NUMBER"
            gh pr edit $PR_NUMBER --base ${GITHUB_REF##*/}
          done
